### ISSUE TITLE
RTX 5090 - Installation is not working smooth (yet)

### ISSUE THREAD

**Issue by AlonDan** [FranckyB/Voice-Clone-Studio#96]
Hi, I've noticed the latest version with Fish Speech - S2 Pro is now included and I wanted to try it out.
I had a feeling installing it on RTX 5090 will be hell, and even with the 1-Click-Installer it is.

I also tried "ALL DEFAULT" but I got the same error, so I decided before I'll fix it with AI help (since it's jiberish for me) I will share my feedback and hopefully it will help you fix it. ❤️

---

### SUGGESTION: 
it seems like there is a Auto-Timer to select options and it's too fast, I would highly recommend to cancel this auto-select options, I guess it does the default but it's just not user-friendly, if you let the users choose, an invisible timer doesn't really help.

I did choose the latest options (Cuda 13, etc.. things to make it work) but I keep getting errors when trying to run it.
Eventually like the old version which had lots of issues with RTX 5090 (probably with 50xx series) it's not working as smooth for example like AI-TOOLKIT Easy Installer (just for comparison of 1 click installation that just works).

So I'll share the first error, but probably I'll solve it step by step with Gemini / GPT like I did last time, but the reason I share it is that you'll hopefully improve the installation and maybe even add Auto-Update whenever it runs (just like how **AI-Toolkit Easy Installer** works, as a reference)
because this project is WONDERFUL! and I hope to see it just keep growing with more upcoming TTS and allow to TRAIN / Fine-Tune our own models.

My personal with training VibeVoice with 7B was really good with the older version (I did had to fool the naming of the LARGE model but I remember you said you fixed that).

--

Usually whenever I fix the 1st error there is another one and another one... so for now I'll just drop the very first error I get:

This happened after I tried to generate Fish Speech - S2 Pro, not sure how many errors will appear after I'll solve this one, and also not sure how many errors will appear once I'll try to train my own Fish Speech - S2 Pro (which is my next goal)

### THE ERROR:

```
❌ Error generating audio: RuntimeError: Failed to run autotuning code block: 'KernelMetadata' object has no attribute 'cluster_dims'

Set TORCHDYNAMO_VERBOSE=1 for the internal stack trace (please do this especially if you're reporting a bug to PyTorch). For even more developer context, set TORCH_LOGS="+dynamo"
```

I hope this feedback helps a bit 🙏
please keep up the good work, this is defiantly one of the best TRAINING AUDIO projects and the most user-friendly one GUI-WISE you made it great, and I'll be happy to suggest more improvements (as a designer and a user) but first things first, make the ONE-CLICK INSTALLATION - works smooth for the RTX 50xx series with no errors.
I highly suggest to look what **AI-TOOLKIT Easy Installer** did to make it work on ALL GPU without even menus, just automatically works like some sort of black magic.

**Comment by AlonDan** [comment]
OK, so since RTX 5090 works with sm120 the CUDA 13.0 didn't work for some reason but it sure worked on the latest NIGHTLY version of CUDA 128, so if that helps you with the auto-install. please give it a try.

Gemini explained that CUDA 13.0 had issues with some other stuff, while 12.8 Nightly is perfect (also very impressive with the test I did about 2-3 seconds for a simple random sentence)

--

Please look at my new [**QOL SUGGESTION**](https://github.com/FranckyB/Voice-Clone-Studio/discussions/97) - https://github.com/FranckyB/Voice-Clone-Studio/discussions/97 👍
I'll be happy to share feedback while helping design and improve more cool ideas to make Voice-Clone-Studio even better!

**Comment by AlonDan** [comment]
### UPDATE:

laynch.bat is not the best for the RTX 5090 so I use this one:

```
@echo off
echo ========================================
echo   Voice Clone Studio - Optimized Launcher
echo   (Optimized for RTX 50-series / sm120)
echo ========================================
echo.

:: Activate the virtual environment
call venv\Scripts\activate.bat

:: Enable Scaled Dot Product Attention (SDPA) for better memory management on Blackwell GPUs
set TORCH_CUDNN_SDPA_ENABLED=1

:: Note: We do NOT disable TORCH_COMPILE because Kernel Caching 
:: provides significant speedups once the initial build is complete.

echo Starting Voice Clone Studio...
echo.

:: Launch the application
python voice_clone_studio.py

pause
```

I left the comments on so you can see what Gemini did, all I can say it works 100% full speed perfect after what I mentioned above so you may want to create an EXTRA batch file, for me I just named it:

### Launch_RTX-5090.bat

so it's not too bad to have the default launch.bat but also the one for RTX 50xx as additional one, can't harm if we'll have it.

**Comment by FranckyB** [comment]
What version of Python are you using.  
The recommended version is 3.11

Last I checked, it worked fine with a 5090, as this is what I have too.

But I do know that a while back update in some python packages broke things and I had to path the launcher to explicitly specify what version to install for some package..   Perhaps this is happening again.  (Though I did do a fresh install last week with no issues)

I'll remove the timed install for the setup.

**Comment by AlonDan** [comment]
In my case I have 2 python versions installed:  3.13 and 3.10 
From my experience what works best so far with sm120 is python 3.10 and Cuda 12.8 (I used nightly, but it seems like the newest stable also works).

But honestly, whatever MAGIC they did - what I highly suggest is to look what **AI-TOOLKIT Easy Installer** ureses because they install everything in 1 click as well but I never had to manually fix after installation it just works.

**Comment by FranckyB** [comment]
AI-Tookit is ONE app...

Voice-Clone-Studio is a bundle of Multiple engines all squeezed in together, all creating conflict with one another.  
So the balance to get everything working is quite a headache.
Every time a new engine gets added makes it worst.

I deleted my venv and created it anew and I can see errors now too, so a package has changed... 🤦

I'd Really recommend you install 3.11 and I'll update the setup when I find the culprit.

**Comment by AlonDan** [comment]
Thanks for explaining, I actually had lots of issues with 3.11 so I just don't use it with my RTX 5090 everything works mostly fine with 3.10 and 3.13 even 3.12 had issues with other repos, so I guess I'll have to fix the issues myself whenever you update because I do like this project a lot, sure fixing manually takes some extra time but at least it works at the end.

---

OFF TOPIC: (feel free to ignore that part)
I just realize the download models is weird with Vibe Voice, but I'm not opening an issue until I'm sure what happens there... for now I just renamed the model name, it may be because the old Vibe Voice trained used the large model and it downloads by default small version at least that's what Gemini explains, but I had this issue before and I just renamed to the small model.
Also I think the newest version download the models to whatever secret folder now, instead to the actual MODELS inside the project which was much more convenient IMO, 
but again... I'm mentioned it just because I saw it while typing this and I don't want to open an issue if I'm not sure what actually happens... that's why this is OFF TOPIC.

**Comment by FranckyB** [comment]
I'm downloading using Hugginface libs, so they get downloaded to the 'default' Hugginface folder:
C:\Users\<username>\.cache\huggingface\hub

In preferences there is an option to download the modesl to the app dir instead.  Though it doesn't include newer models.

**Comment by FranckyB** [comment]
So I've made a requirement_windows with specific package version, but also changed the default to install everything.
I suspect, since I developed it this way, that having everything work, needs everything installed 😅
So with these specific packages and choosing 1 for everything at install is simply the best option.

You are free then in settings to simply not show what you don't want.  
You will Need python 3.11 for this.

This now install fine again on my 5090

**Comment by AlonDan** [comment]
Thanks!
Will it be possible to train Fish Speech - S2 Pro  locally just like Vibe Voice in the next update?
